stages:
  - check-license

check-license_job:
  stage: check-license
  variables:
      EXPECTED_LIC_STR: "SPDX-License-Identifier: GPL-2.0-or-later OR MIT"
  script:
    - cd $CI_PROJECT_DIR/overlays
    - |
        for DTO in $(ls *dts)
        do
        head -n 1 $DTO | \
            grep -q "${EXPECTED_LIC_STR}" || \
            ERRMSG="${ERRMSG}License mssing, wrong or not on 1st line: ${DTO} \n"
        done
        if [ "${ERRMSG}" ]
        then
            echo -ne $ERRMSG
            exit 1
        fi
